/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AiPlan = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'basedOnExamType' : IDL.Text,
  'studentId' : IDL.Nat,
  'aiPlanText' : IDL.Text,
  'improvementTargetPercentage' : IDL.Float64,
  'planVersion' : IDL.Nat,
  'basedOnAverage' : IDL.Float64,
  'generatedDate' : Time,
  'performanceSnapshot' : IDL.Text,
});
export const AdminStats = IDL.Record({
  'weakCount' : IDL.Nat,
  'totalStudents' : IDL.Nat,
  'highRiskCount' : IDL.Nat,
});
export const Feedback = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Nat,
  'subject' : IDL.Text,
  'behaviour' : IDL.Nat,
  'participation' : IDL.Nat,
  'homeworkCompletion' : IDL.Bool,
  'conceptClarity' : IDL.Nat,
  'remarks' : IDL.Text,
});
export const Mark = IDL.Record({
  'id' : IDL.Nat,
  'marks' : IDL.Float64,
  'studentId' : IDL.Nat,
  'subject' : IDL.Text,
  'maxMarks' : IDL.Float64,
  'examType' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'parentPhone' : IDL.Text,
  'section' : IDL.Text,
  'rollNumber' : IDL.Text,
  'className' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const StudentAnalysis = IDL.Record({
  'isHighRisk' : IDL.Bool,
  'overallAverage' : IDL.Float64,
  'isWeak' : IDL.Bool,
  'weakSubjects' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFeedback' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Bool,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addMark' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changePassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'constructor' : IDL.Func([], [], ['oneway']),
  'createStudent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createTeacherAccount' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteStudent' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'deleteTeacherAccount' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'generateAndSaveAiPlan' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Bool],
      [IDL.Variant({ 'ok' : AiPlan, 'err' : IDL.Text })],
      [],
    ),
  'generateImprovementPlan' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], []),
  'getAdminStats' : IDL.Func([IDL.Text], [AdminStats], ['query']),
  'getAiPlansByStudent' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(AiPlan)],
      ['query'],
    ),
  'getAllFeedback' : IDL.Func([IDL.Text], [IDL.Vec(Feedback)], ['query']),
  'getAllMarks' : IDL.Func([IDL.Text], [IDL.Vec(Mark)], ['query']),
  'getAllStudents' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentUserInfo' : IDL.Func(
      [IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'username' : IDL.Text,
            'name' : IDL.Text,
            'role' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'getFeedbackByStudent' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(Feedback)],
      ['query'],
    ),
  'getLatestAiPlan' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(AiPlan)],
      ['query'],
    ),
  'getMarksByStudent' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(Mark)],
      ['query'],
    ),
  'getStudent' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Opt(Student)], ['query']),
  'getStudentAnalysis' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [StudentAnalysis],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeApp' : IDL.Func([], [IDL.Text], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listTeacherAccounts' : IDL.Func(
      [IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Vec(
            IDL.Record({
              'username' : IDL.Text,
              'name' : IDL.Text,
              'role' : IDL.Text,
            })
          ),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'token' : IDL.Text,
            'name' : IDL.Text,
            'role' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'logout' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAiPlanStatus' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateStudent' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'validateSession' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'username' : IDL.Text,
            'name' : IDL.Text,
            'createdAt' : Time,
            'role' : IDL.Text,
          })
        ),
      ],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AiPlan = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'basedOnExamType' : IDL.Text,
    'studentId' : IDL.Nat,
    'aiPlanText' : IDL.Text,
    'improvementTargetPercentage' : IDL.Float64,
    'planVersion' : IDL.Nat,
    'basedOnAverage' : IDL.Float64,
    'generatedDate' : Time,
    'performanceSnapshot' : IDL.Text,
  });
  const AdminStats = IDL.Record({
    'weakCount' : IDL.Nat,
    'totalStudents' : IDL.Nat,
    'highRiskCount' : IDL.Nat,
  });
  const Feedback = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Nat,
    'subject' : IDL.Text,
    'behaviour' : IDL.Nat,
    'participation' : IDL.Nat,
    'homeworkCompletion' : IDL.Bool,
    'conceptClarity' : IDL.Nat,
    'remarks' : IDL.Text,
  });
  const Mark = IDL.Record({
    'id' : IDL.Nat,
    'marks' : IDL.Float64,
    'studentId' : IDL.Nat,
    'subject' : IDL.Text,
    'maxMarks' : IDL.Float64,
    'examType' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'parentPhone' : IDL.Text,
    'section' : IDL.Text,
    'rollNumber' : IDL.Text,
    'className' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const StudentAnalysis = IDL.Record({
    'isHighRisk' : IDL.Bool,
    'overallAverage' : IDL.Float64,
    'isWeak' : IDL.Bool,
    'weakSubjects' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFeedback' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Bool,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addMark' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changePassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'constructor' : IDL.Func([], [], ['oneway']),
    'createStudent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createTeacherAccount' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteStudent' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'deleteTeacherAccount' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'generateAndSaveAiPlan' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Bool],
        [IDL.Variant({ 'ok' : AiPlan, 'err' : IDL.Text })],
        [],
      ),
    'generateImprovementPlan' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], []),
    'getAdminStats' : IDL.Func([IDL.Text], [AdminStats], ['query']),
    'getAiPlansByStudent' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(AiPlan)],
        ['query'],
      ),
    'getAllFeedback' : IDL.Func([IDL.Text], [IDL.Vec(Feedback)], ['query']),
    'getAllMarks' : IDL.Func([IDL.Text], [IDL.Vec(Mark)], ['query']),
    'getAllStudents' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentUserInfo' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'username' : IDL.Text,
              'name' : IDL.Text,
              'role' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'getFeedbackByStudent' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(Feedback)],
        ['query'],
      ),
    'getLatestAiPlan' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(AiPlan)],
        ['query'],
      ),
    'getMarksByStudent' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(Mark)],
        ['query'],
      ),
    'getStudent' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Opt(Student)], ['query']),
    'getStudentAnalysis' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [StudentAnalysis],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeApp' : IDL.Func([], [IDL.Text], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listTeacherAccounts' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Vec(
              IDL.Record({
                'username' : IDL.Text,
                'name' : IDL.Text,
                'role' : IDL.Text,
              })
            ),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'token' : IDL.Text,
              'name' : IDL.Text,
              'role' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'logout' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAiPlanStatus' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateStudent' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'validateSession' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'username' : IDL.Text,
              'name' : IDL.Text,
              'createdAt' : Time,
              'role' : IDL.Text,
            })
          ),
        ],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };