/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'weakCount' : bigint,
  'totalStudents' : bigint,
  'highRiskCount' : bigint,
}
export interface AiPlan {
  'id' : bigint,
  'status' : string,
  'basedOnExamType' : string,
  'studentId' : bigint,
  'aiPlanText' : string,
  'improvementTargetPercentage' : number,
  'planVersion' : bigint,
  'basedOnAverage' : number,
  'generatedDate' : Time,
  'performanceSnapshot' : string,
}
export interface Feedback {
  'id' : bigint,
  'studentId' : bigint,
  'subject' : string,
  'behaviour' : bigint,
  'participation' : bigint,
  'homeworkCompletion' : boolean,
  'conceptClarity' : bigint,
  'remarks' : string,
}
export interface Mark {
  'id' : bigint,
  'marks' : number,
  'studentId' : bigint,
  'subject' : string,
  'maxMarks' : number,
  'examType' : string,
}
export interface Student {
  'id' : bigint,
  'name' : string,
  'parentPhone' : string,
  'section' : string,
  'rollNumber' : string,
  'className' : string,
}
export interface StudentAnalysis {
  'isHighRisk' : boolean,
  'overallAverage' : number,
  'isWeak' : boolean,
  'weakSubjects' : Array<string>,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFeedback' : ActorMethod<
    [string, bigint, string, bigint, boolean, bigint, bigint, string],
    bigint
  >,
  'addMark' : ActorMethod<
    [string, bigint, string, string, number, number],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changePassword' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'constructor' : ActorMethod<[], undefined>,
  'createStudent' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'createTeacherAccount' : ActorMethod<
    [string, string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteStudent' : ActorMethod<[string, bigint], boolean>,
  'deleteTeacherAccount' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'generateAndSaveAiPlan' : ActorMethod<
    [string, bigint, boolean],
    { 'ok' : AiPlan } |
      { 'err' : string }
  >,
  'generateImprovementPlan' : ActorMethod<[string, bigint], string>,
  'getAdminStats' : ActorMethod<[string], AdminStats>,
  'getAiPlansByStudent' : ActorMethod<[string, bigint], Array<AiPlan>>,
  'getAllFeedback' : ActorMethod<[string], Array<Feedback>>,
  'getAllMarks' : ActorMethod<[string], Array<Mark>>,
  'getAllStudents' : ActorMethod<[string], Array<Student>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentUserInfo' : ActorMethod<
    [string],
    { 'ok' : { 'username' : string, 'name' : string, 'role' : string } } |
      { 'err' : string }
  >,
  'getFeedbackByStudent' : ActorMethod<[string, bigint], Array<Feedback>>,
  'getLatestAiPlan' : ActorMethod<[string, bigint], [] | [AiPlan]>,
  'getMarksByStudent' : ActorMethod<[string, bigint], Array<Mark>>,
  'getStudent' : ActorMethod<[string, bigint], [] | [Student]>,
  'getStudentAnalysis' : ActorMethod<[string, bigint], StudentAnalysis>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeApp' : ActorMethod<[], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listTeacherAccounts' : ActorMethod<
    [string],
    {
        'ok' : Array<{ 'username' : string, 'name' : string, 'role' : string }>
      } |
      { 'err' : string }
  >,
  'login' : ActorMethod<
    [string, string],
    { 'ok' : { 'token' : string, 'name' : string, 'role' : string } } |
      { 'err' : string }
  >,
  'logout' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAiPlanStatus' : ActorMethod<
    [string, bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateStudent' : ActorMethod<
    [string, bigint, string, string, string, string, string],
    boolean
  >,
  'validateSession' : ActorMethod<
    [string],
    [] | [
      {
        'username' : string,
        'name' : string,
        'createdAt' : Time,
        'role' : string,
      }
    ]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];